"""add unique constraint on pull_requests repo_id github_pr_number

Revision ID: 9eb55d860cd7
Revises: c19809424e15
Create Date: 2026-05-29 22:03:21.827188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb55d860cd7'
down_revision: Union[str, Sequence[str], None] = 'c19809424e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_pr_repo_number', 'pull_requests', ['repo_id', 'github_pr_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_pr_repo_number', 'pull_requests', type_='unique')
    # ### end Alembic commands ###
